class_name SkillActivationOptimalTargets

enum e{
	ALLY, 
	OPPONENT, 
	ALLY_LEAST_HEALTH, 
	ALLY_AFFLICTED_STATUS_EFFECT, 
	BOSS, OPPONENT_HIGHEST_DANGER, 
	OPPONENT_LOWEST_HEALTH, 
	OPPONENT_HIGHEST_HEALTH,
	NONE
}
